import { Controller, Get } from '@nestjs/common';

@Controller('content')
export class ContentController {
  @Get()
  getAll() {
    return {
      app: {
        brand: 'edge-ctrl',
        tagline: 'Edge Node Network Manager',
      },
      nav: {
        dashboard: 'Dashboard',
        modem: 'Control de módem',
        audit: 'Auditoría de red',
        camera: 'Cámara',
        intercom: 'Intercom',
        alerts: 'Alertas',
        settings: 'Ajustes',
        login: 'Iniciar sesión',
        register: 'Crear cuenta',
        logout: 'Cerrar sesión',
      },
      auth: {
        loginTitle: 'Iniciar sesión',
        loginSubtitle: 'Ingresá tus credenciales para acceder al panel',
        emailLabel: 'Email',
        passwordLabel: 'Contraseña',
        loginButton: 'Ingresar',
        loggingIn: 'Ingresando…',
        noAccount: '¿No tenés cuenta?',
        registerLink: 'Crear cuenta',
        registerTitle: 'Crear cuenta',
        registerSubtitle: 'Registrate para acceder al panel de administración',
        displayNameLabel: 'Nombre',
        registerButton: 'Registrarse',
        registering: 'Registrando…',
        haveAccount: '¿Ya tenés cuenta?',
        loginLink: 'Iniciar sesión',
      },
      dashboard: {
        title: 'Dashboard',
        latency: 'Latencia',
        battery: 'Batería Edge',
        download: 'Descarga',
        uploadPing: 'Subida / Ping',
        devices: 'Dispositivos',
        nodeStatus: 'Estado del nodo',
        ms: 'ms',
        mbps: 'Mbps',
        charging: 'cargando',
        onBattery: 'en red',
        connected: 'conectados',
        noServer: 'Sin servidor configurado',
        noNode: 'No hay un nodo vinculado todavía',
      },
      modem: {
        title: 'Control de módem',
        connect: 'modem.connect',
        status: 'status: ONLINE',
        rebootBtn: 'Reiniciar módem',
      },
      audit: {
        title: 'Auditoría de red',
        scanCmd: 'edge-scan --network 192.168.1.0/24',
        desc1: 'El edge node escanea la red LAN cada 15 minutos',
        desc2: 'detecta dispositivos por ARP + ICMP ping',
        scanBtn: 'Escanear ahora',
      },
      camera: {
        title: 'Cámara remota',
        live: 'Transmisión en vivo desde el edge node',
        hint: 'WebRTC con TURN/STUN — requiere sesión activa',
        startBtn: 'Iniciar cámara',
      },
      intercom: {
        title: 'Interfono bidireccional',
        cmdInit: 'intercom --session iniciar',
        desc1: 'Audio bidireccional WebRTC con el edge node',
        desc2: 'El celular Samsung S9 actúa como interfono IP',
        startBtn: 'Iniciar intercom',
      },
      alerts: {
        title: 'Centro de alertas',
        cmd: 'edge-node --alerts',
        desc1: 'Alertas de latencia, dispositivos nuevos, batería baja',
        desc2: 'Notificaciones push vía FCM al edge node',
      },
      settings: {
        title: 'Ajustes del nodo',
        cmd: 'edge-node --config',
        chargeLimit: 'Límite de carga: 80% (prolonga vida batería S9)',
        scanInterval: 'Escaneo LAN: cada 15 min',
        pingInterval: 'Ping latencia: cada 3 min',
        alertThreshold: 'Alerta si latencia > 300 ms',
        serverPanel: 'Servidor (tunnel)',
        apiLabel: 'api:',
        changeBtn: 'cambiar',
        closeBtn: 'cerrar',
        saveBtn: 'guardar',
        defaultBtn: 'default',
        rediscoverBtn: 'redescubrir',
        discovering: 'descubriendo…',
        tunnelActive: 'tunnel activo',
        tunnelUndetected: 'tunnel no detectado (accesible solo en LAN)',
        noContact: 'no se pudo contactar el servidor',
      },
    };
  }
}
